from __future__ import annotations

from enum import StrEnum


DOMAIN_VOCABULARY_VERSION = "dichiarazioni-pubbliche-domain-vocabulary-v1"
CLAIM_TYPE_VERSION = "atomic-claim-v1"
VERIFICATION_ASSESSMENT_VERSION = "deterministic-verification-v2"
FINDING_PUBLICATION_STATUS_VERSION = "finding-publication-v1"
RELATION_VERSION = "claim-relation-v1"
INFERENCE_VERSION = "reasoned-inference-v1"


class ClaimType(StrEnum):
    ARITHMETIC = "ARITHMETIC"
    CAUSAL_CLAIM = "CAUSAL_CLAIM"
    CURRENT_FOREIGN_POLICY = "CURRENT_FOREIGN_POLICY"
    CURRENT_POLICY = "CURRENT_POLICY"
    CURRENT_POLICY_POSITION = "CURRENT_POLICY_POSITION"
    DISTRIBUTIONAL_CLAIM = "DISTRIBUTIONAL_CLAIM"
    ELECTION_PREDICTION = "ELECTION_PREDICTION"
    FISCAL_INFERENCE = "FISCAL_INFERENCE"
    GROUP_MOTIVE = "GROUP_MOTIVE"
    HISTORICAL_ATTRIBUTION = "HISTORICAL_ATTRIBUTION"
    HISTORICAL_CLAIM = "HISTORICAL_CLAIM"
    HISTORICAL_POLITICAL = "HISTORICAL_POLITICAL"
    LEGAL_POLICY_STATUS = "LEGAL_POLICY_STATUS"
    LEGAL_QUOTE = "LEGAL_QUOTE"
    MOTIVE_ATTRIBUTION = "MOTIVE_ATTRIBUTION"
    NUMERIC_STATISTIC = "NUMERIC_STATISTIC"
    POLICY_DIFFERENCE = "POLICY_DIFFERENCE"
    POLICY_SCOPE = "POLICY_SCOPE"
    POLITICAL_ATTRIBUTION = "POLITICAL_ATTRIBUTION"
    PRICE_STATISTIC = "PRICE_STATISTIC"
    QUOTE_ATTRIBUTION = "QUOTE_ATTRIBUTION"
    RHETORICAL_GENERALIZATION = "RHETORICAL_GENERALIZATION"
    SYSTEMIC_CLAIM = "SYSTEMIC_CLAIM"
    SYSTEMIC_INFERENCE = "SYSTEMIC_INFERENCE"
    TAX_RATE = "TAX_RATE"
    VALUE_JUDGMENT = "VALUE_JUDGMENT"


class VerificationAssessment(StrEnum):
    SUPPORTED = "SUPPORTED"
    FACTUALLY_FALSE = "FACTUALLY_FALSE"
    OUTDATED_DATA = "OUTDATED_DATA"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    UNRESOLVED = "UNRESOLVED"


class FindingPublicationStatus(StrEnum):
    INTERNAL_CANDIDATE = "INTERNAL_CANDIDATE"
    PUBLISH = "PUBLISH"
    NO_FINDING = "NO_FINDING"
    NEEDS_MORE_EVIDENCE = "NEEDS_MORE_EVIDENCE"
    UNRESOLVED = "UNRESOLVED"
    POLICY_HOLD = "POLICY_HOLD"
    DISPUTED = "DISPUTED"
    CORRECTED = "CORRECTED"
    RETRACTED = "RETRACTED"


class RelationCandidateType(StrEnum):
    NO_RELATION = "NO_RELATION"
    RELATED_TOPIC = "RELATED_TOPIC"
    SAME_PROPOSITION = "SAME_PROPOSITION"
    POSITION_CHANGE_CANDIDATE = "POSITION_CHANGE_CANDIDATE"
    CONTRADICTION_CANDIDATE = "CONTRADICTION_CANDIDATE"


class InferenceKind(StrEnum):
    DEDUCTIVE = "DEDUCTIVE"
    ABDUCTIVE_BEST_EXPLANATION = "ABDUCTIVE_BEST_EXPLANATION"
    STATISTICAL = "STATISTICAL"
    EXCLUSION = "EXCLUSION"
    COMPOSITE = "COMPOSITE"


class InferenceSupportLevel(StrEnum):
    DIRECT = "DIRECT"
    VERY_STRONG = "VERY_STRONG"
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    WEAK = "WEAK"
    INDETERMINATE = "INDETERMINATE"


class InferenceRiskClass(StrEnum):
    STANDARD = "STANDARD"
    SENSITIVE_PERSON = "SENSITIVE_PERSON"
    CRIMINAL_ALLEGATION = "CRIMINAL_ALLEGATION"
    IDENTITY_ATTRIBUTION = "IDENTITY_ATTRIBUTION"
    INTENT_ATTRIBUTION = "INTENT_ATTRIBUTION"


class EvaluationOutcome(StrEnum):
    SUPPORTED = "SUPPORTED"
    FACTUALLY_FALSE = "FACTUALLY_FALSE"
    OUTDATED_DATA = "OUTDATED_DATA"
    NO_CONTRADICTION_ESTABLISHED = "NO_CONTRADICTION_ESTABLISHED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


VOCABULARIES = {
    "claim_type": (CLAIM_TYPE_VERSION, tuple(item.value for item in ClaimType)),
    "verification_assessment": (
        VERIFICATION_ASSESSMENT_VERSION,
        tuple(item.value for item in VerificationAssessment),
    ),
    "finding_publication_status": (
        FINDING_PUBLICATION_STATUS_VERSION,
        tuple(item.value for item in FindingPublicationStatus),
    ),
    "relation_candidate": (
        RELATION_VERSION,
        tuple(item.value for item in RelationCandidateType),
    ),
    "reasoned_inference": (
        INFERENCE_VERSION,
        tuple(item.value for item in InferenceKind),
    ),
}


__all__ = [
    "CLAIM_TYPE_VERSION",
    "ClaimType",
    "DOMAIN_VOCABULARY_VERSION",
    "EvaluationOutcome",
    "FINDING_PUBLICATION_STATUS_VERSION",
    "FindingPublicationStatus",
    "INFERENCE_VERSION",
    "InferenceKind",
    "InferenceRiskClass",
    "InferenceSupportLevel",
    "RELATION_VERSION",
    "RelationCandidateType",
    "VERIFICATION_ASSESSMENT_VERSION",
    "VOCABULARIES",
    "VerificationAssessment",
]
