from pathlib import Path
root = Path(__file__).resolve().parent
css=r'''
@font-face{font-family:NewsreaderDP;src:url('../../web/dist/_astro/newsreader-latin-wght-normal.CCVVNp6i.woff2') format('woff2');font-weight:200 800;font-style:normal;font-display:swap}
@font-face{font-family:PlexDP;src:url('../../web/dist/_astro/ibm-plex-sans-latin-wght-normal.IvpUvPa2.woff2') format('woff2');font-weight:200 800;font-style:normal;font-display:swap}
@font-face{font-family:PlexMonoDP;src:url('../../web/dist/_astro/ibm-plex-mono-latin-400-normal.DMJ8VG8y.woff2') format('woff2');font-weight:400;font-style:normal;font-display:swap}
:root{--paper:#f5f5f1;--raised:#fff;--ink:#101827;--ink2:#3c4657;--muted:#667080;--line:#c8ccc5;--line2:#9ba39a;--blue:#1457d9;--blue2:#0b3890;--select:#e1e9f8;--green:#195f45;--red:#8b2830;--amber:#6c4d0d;--slate:#3f5870;--sans:PlexDP,system-ui,sans-serif;--serif:NewsreaderDP,Georgia,serif;--mono:PlexMonoDP,monospace}
*{box-sizing:border-box}html{background:var(--paper);color:var(--ink);font-family:var(--sans);font-size:16px}body{margin:0;background:var(--paper)}a{color:inherit}.shell{width:min(1240px,calc(100% - 64px));margin:0 auto}.topline{border-bottom:1px solid var(--line);font-size:12px;color:var(--ink2)}.topline .shell{display:flex;justify-content:space-between;padding:8px 0}.header{border-bottom:1px solid var(--line);background:rgba(245,245,241,.96)}.header .shell{height:72px;display:grid;grid-template-columns:300px 1fr 160px;align-items:center}.brand{display:flex;align-items:center;gap:11px;text-decoration:none}.mark{font-family:var(--serif);font-size:34px;line-height:1;color:var(--blue);font-weight:700}.brand b{font-family:var(--serif);font-size:24px;line-height:.95}.nav{display:flex;gap:32px;justify-content:center;font-size:14px}.nav a{text-decoration:none}.nav a.active{font-weight:650;text-decoration:underline;text-underline-offset:7px;text-decoration-color:var(--blue);text-decoration-thickness:2px}.head-search{justify-self:end;font-size:14px;color:var(--ink2)}
main{padding-bottom:74px}.hero{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(360px,.8fr);gap:80px;padding:90px 0 76px;border-bottom:1px solid var(--ink)}h1,h2,h3,p{margin-top:0}.display{font-family:var(--serif);font-size:76px;line-height:.93;letter-spacing:-.035em;font-weight:620;max-width:760px;margin-bottom:30px}.lede{font-size:20px;line-height:1.5;max-width:690px;color:var(--ink2)}.searchbox{align-self:end;border-top:1px solid var(--ink);padding-top:22px}.searchbox label{display:block;font-weight:650;margin-bottom:14px}.search{display:grid;grid-template-columns:1fr auto;border:1px solid var(--line2);background:var(--raised);min-height:58px}.search input{border:0;background:transparent;padding:0 18px;font:inherit;color:var(--ink);outline:none}.search button{border:0;border-left:1px solid var(--line);background:var(--ink);color:white;padding:0 22px;font-weight:650}.hint{font-size:13px;color:var(--muted);line-height:1.45;margin-top:12px}.section{padding:58px 0;border-bottom:1px solid var(--line)}.sectionhead{display:grid;grid-template-columns:1fr auto;align-items:end;margin-bottom:22px}.sectionhead h2{font-family:var(--serif);font-size:34px;line-height:1;font-weight:580;margin:0}.sectionhead p{margin:8px 0 0;color:var(--muted)}.link{color:var(--blue2);font-weight:650;font-size:14px;text-decoration:none}.claimlist{border-top:1px solid var(--ink)}.claimrow{display:grid;grid-template-columns:118px minmax(0,1fr) 240px 34px;gap:22px;align-items:center;padding:22px 0;border-bottom:1px solid var(--line);min-height:114px}.date{font-family:var(--mono);font-size:13px;color:var(--muted);font-variant-numeric:tabular-nums}.type{font-size:11px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:var(--ink2);margin-bottom:6px}.claim{font-family:var(--serif);font-size:25px;line-height:1.16;font-weight:570;text-decoration:none}.meta{font-size:13px;color:var(--muted);margin-top:7px}.status{justify-self:start;font-weight:650;font-size:13px;display:flex;gap:8px;align-items:center}.dot{width:8px;height:8px;border-radius:50%;border:1px solid currentColor;background:transparent}.supported{color:var(--green)}.false{color:var(--red)}.imprecise{color:var(--amber)}.unresolved{color:var(--slate)}.arrow{font-size:24px;color:var(--blue)}
.mediafeature{display:grid;grid-template-columns:420px 1fr;gap:40px;align-items:center}.mediaframe{aspect-ratio:16/9;background:#171a1f;color:#fff;display:flex;align-items:flex-end;padding:22px;position:relative;overflow:hidden}.mediaframe:before{content:'';position:absolute;inset:0;background:linear-gradient(130deg,#242933 0 45%,#11151c 45% 100%)}.mediaframe .time{position:relative;font:13px var(--mono);color:#d6d9df}.mediafeature h3{font-family:var(--serif);font-size:34px;margin-bottom:12px}.moments{display:flex;gap:28px;margin-top:25px}.moment{border-left:1px solid var(--blue);padding-left:13px;font-size:14px}.moment b{font-family:var(--mono);font-size:12px;color:var(--blue2)}
.pagehead{padding:72px 0 42px;border-bottom:1px solid var(--ink)}.pagehead h1{font-family:var(--serif);font-size:58px;line-height:1;letter-spacing:-.025em;font-weight:600;margin-bottom:18px}.pagehead .lede{font-size:18px;max-width:760px}.toolbar{padding:30px 0 22px;border-bottom:1px solid var(--line)}.toolbar .search{max-width:780px}.controls{display:flex;gap:12px;align-items:center;margin-top:18px}.control{border:1px solid var(--line2);background:var(--raised);padding:10px 12px;font:14px var(--sans);border-radius:3px}.count{margin-left:auto;color:var(--muted);font-size:14px}.explorerow{grid-template-columns:60px 110px minmax(0,1fr) 220px 30px}.rank{font-family:var(--serif);font-size:28px;color:#9aa4b0}
.facthead{padding:62px 0;border-bottom:1px solid var(--ink)}.factgrid{display:grid;grid-template-columns:minmax(0,1fr) 260px;gap:80px}.claimtitle{font-family:var(--serif);font-size:58px;line-height:1.03;letter-spacing:-.028em;font-weight:580;margin:0 0 24px;max-width:850px}.factmeta{font-size:14px;color:var(--ink2);display:flex;gap:10px;flex-wrap:wrap}.factstatus{padding-left:24px;border-left:1px solid var(--line)}.factstatus small{display:block;color:var(--muted);margin-bottom:12px}.factstatus .status{font-size:16px}.factbody{display:grid;grid-template-columns:minmax(0,760px) 300px;gap:100px;padding-top:54px}.prose{font-family:var(--serif);font-size:19px;line-height:1.62}.prose .answer{font-size:26px;line-height:1.43;color:var(--ink);font-weight:520;margin-bottom:42px}.prose h2{font-family:var(--sans);font-size:18px;margin:44px 0 14px}.marker{font-family:var(--sans);font-size:12px;color:var(--blue2);vertical-align:super}.sourcerow{display:grid;grid-template-columns:46px 1fr 120px 24px;padding:16px 0;border-top:1px solid var(--line);font-family:var(--sans);font-size:14px;text-decoration:none}.sourcerow:last-child{border-bottom:1px solid var(--line)}.sourceidx{font-family:var(--mono);color:var(--blue2)}.rail{font-size:14px}.railblock{padding:0 0 22px;margin-bottom:22px;border-bottom:1px solid var(--line)}.railblock small{display:block;color:var(--muted);margin-bottom:7px}.railblock h3{font-family:var(--serif);font-size:21px;margin-bottom:4px}
.recordhead{padding:72px 0 40px;border-bottom:1px solid var(--ink)}.recordgrid{display:grid;grid-template-columns:1fr 360px;gap:80px}.recordhead h1{font-family:var(--serif);font-size:62px;font-weight:600;letter-spacing:-.03em;margin-bottom:8px}.role{font-size:18px;color:var(--ink2)}.recordnote{max-width:730px;color:var(--muted);margin-top:24px}.filterbar{display:grid;grid-template-columns:180px 250px 145px 145px auto;gap:12px;padding:26px 0;border-bottom:1px solid var(--line)}.filterbar label{font-size:12px;color:var(--muted)}.filterbar select,.filterbar input{width:100%;margin-top:7px;border:1px solid var(--line2);background:var(--raised);padding:9px;font:13px var(--sans)}.reset{align-self:end;background:none;border:0;color:var(--blue2);font-weight:650;padding:10px}.timeline .claimrow{grid-template-columns:150px minmax(0,1fr) 210px 30px}.timeline .date{font-size:14px}.rolehistory{margin-top:22px;padding-top:18px;border-top:1px solid var(--line);display:flex;gap:28px;font-size:13px;color:var(--muted)}
.audithead{padding:64px 0 38px;border-bottom:1px solid var(--ink)}.audithead h1{font-family:var(--serif);font-size:52px;font-weight:600;letter-spacing:-.025em;margin-bottom:12px}.auditmeta{display:flex;gap:10px;color:var(--muted);font-size:14px}.auditlayout{display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:46px;padding:42px 0}.player{aspect-ratio:16/9;background:#111720;color:white;display:flex;align-items:center;justify-content:center;position:relative}.play{width:62px;height:62px;border:1px solid #f5f5f1;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:24px}.playercap{position:absolute;left:24px;bottom:18px;font-family:var(--mono);font-size:12px;color:#d7dce5}.tape{margin:22px 0 30px;position:relative;display:flex;justify-content:space-between}.tape:before{content:'';position:absolute;left:4px;right:4px;top:6px;height:1px;background:var(--line2)}.tick{position:relative;background:var(--paper);padding-top:18px;font:12px var(--mono);color:var(--muted)}.tick:before{content:'';position:absolute;top:2px;left:50%;width:8px;height:8px;border-radius:50%;background:var(--paper);border:1px solid var(--line2)}.tick.active{color:var(--blue2);font-weight:700}.tick.active:before{background:var(--blue);border-color:var(--blue)}.auditdetail{border-left:1px solid var(--ink);padding-left:28px}.auditdetail small{color:var(--muted)}.auditdetail h2{font-family:var(--serif);font-size:31px;line-height:1.14;margin:12px 0 18px}.auditdetail p{line-height:1.5;color:var(--ink2)}.auditdetail .sources{margin-top:30px;border-top:1px solid var(--line)}.auditdetail .sources div{padding:13px 0;border-bottom:1px solid var(--line);font-size:13px}.momentrow{display:grid;grid-template-columns:80px 1fr 200px;padding:16px 0;border-top:1px solid var(--line);align-items:center}.momentrow:last-child{border-bottom:1px solid var(--line)}.momentrow .q{font-family:var(--serif);font-size:19px}
.compareintro{max-width:850px}.comparetimeline{position:relative;margin:48px 0 0;padding-left:120px}.comparetimeline:before{content:'';position:absolute;left:78px;top:8px;bottom:20px;width:1px;background:var(--line2)}.event{position:relative;padding:0 0 48px}.event:before{content:'';position:absolute;left:-46px;top:7px;width:10px;height:10px;border-radius:50%;border:1px solid var(--blue);background:var(--paper)}.event .eventdate{position:absolute;left:-120px;top:0;width:72px;font:12px var(--mono);color:var(--muted);text-align:right}.event blockquote{font-family:var(--serif);font-size:32px;line-height:1.18;margin:0 0 12px;max-width:800px}.event .eventmeta{font-size:13px;color:var(--muted)}.event .eventstatus{margin-top:12px}.relationnote{padding:22px 0;border-top:1px solid var(--ink);border-bottom:1px solid var(--ink);max-width:880px;line-height:1.5;color:var(--ink2)}
.method{display:grid;grid-template-columns:minmax(0,760px) 320px;gap:100px;padding:70px 0}.method h1{font-family:var(--serif);font-size:58px;line-height:1.02;letter-spacing:-.025em;font-weight:600;margin-bottom:20px}.methodintro{font-size:20px;line-height:1.55;color:var(--ink2)}.step{display:grid;grid-template-columns:64px 1fr;gap:18px;padding:34px 0;border-top:1px solid var(--line)}.step:last-child{border-bottom:1px solid var(--line)}.stepnum{font:16px var(--mono);color:var(--blue)}.step h2{font-family:var(--serif);font-size:28px;margin-bottom:10px}.step p{line-height:1.55;color:var(--ink2)}.principles{position:sticky;top:30px;border-top:1px solid var(--ink)}.principles h3{font-family:var(--serif);font-size:24px;padding:20px 0 10px}.principles div{padding:18px 0;border-top:1px solid var(--line)}.principles b{display:block;margin-bottom:4px}.principles span{font-size:13px;color:var(--muted);line-height:1.45;display:block}
.footer{border-top:1px solid var(--ink);padding:30px 0 42px}.footer .shell{display:grid;grid-template-columns:1fr auto;gap:30px}.footer b{font-family:var(--serif);font-size:22px}.footlinks{display:flex;gap:24px;font-size:13px}
@media(max-width:900px){.shell{width:min(100% - 32px,1240px)}.header .shell{grid-template-columns:1fr auto}.nav{display:none}.hero,.factgrid,.factbody,.recordgrid,.auditlayout,.method{grid-template-columns:1fr;gap:34px}.display{font-size:52px}.claimrow,.explorerow,.timeline .claimrow{grid-template-columns:90px 1fr}.claimrow>*:nth-child(n+3),.explorerow>*:nth-child(n+4),.timeline .claimrow>*:nth-child(n+3){display:none}.factstatus,.auditdetail{padding-left:0;border-left:0;border-top:1px solid var(--line);padding-top:22px}.filterbar{grid-template-columns:1fr 1fr}.mediafeature{grid-template-columns:1fr}.comparetimeline{padding-left:80px}.event .eventdate{left:-80px;width:48px}.method{padding-top:42px}}
'''

def header(active=""):
    links = [("Esplora", "Esplora"), ("Metodo", "Metodo")]
    nav = "".join(
        f'<a class="{"active" if active == key else ""}" href="#">{label}</a>'
        for key, label in links
    )
    return f"""<div class="topline"><div class="shell"><span>Registro pubblico delle dichiarazioni</span><span>Fonti · tempo · correzioni</span></div></div><header class="header"><div class="shell"><a class="brand"><span class="mark">“</span><b>Dichiarazioni<br>Pubbliche</b></a><nav class="nav">{nav}</nav><div class="head-search">⌕&nbsp;&nbsp;Cerca</div></div></header>"""


def footer():
    return """<footer class="footer"><div class="shell"><div><b>Dichiarazioni Pubbliche</b><div class="hint">La memoria ricercabile di ciò che viene detto in pubblico.</div></div><div class="footlinks"><a>Metodo</a><a>Correzioni</a><a>Dati & API</a><a>Progetto</a><a>Privacy</a></div></div></footer>"""


def page(title, body, active=""):
    return f"""<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>{css}</style></head><body>{header(active)}<main>{body}</main>{footer()}</body></html>"""


rows = [
    ("18 set 2026", "Dato numerico", "“Nel trimestre le esportazioni sono cresciute del 6,2%.”", "Marta Rinaldi · Intervista economica", "Supportata", "supported"),
    ("16 set 2026", "Media", "“Questa piattaforma raggiunge ormai un italiano su tre.”", "Luca Berni · Podcast pubblico", "Da contestualizzare", "imprecise"),
    ("14 set 2026", "Politica pubblica", "“Il provvedimento riduce i tempi medi di attesa di trenta giorni.”", "Anna Serra · Conferenza stampa", "Prove insufficienti", "unresolved"),
    ("12 set 2026", "Tecnologia", "“Il nuovo modello consuma la metà delle risorse a parità di risultato.”", "Davide Conti · Video online", "Supportata", "supported"),
]


def claim_rows(explore=False):
    out = []
    for i, (d, t, c, m, s, cl) in enumerate(rows, 1):
        cls = "claimrow explorerow" if explore else "claimrow"
        rank = f'<div class="rank">{i:02}</div>' if explore else ""
        out.append(
            f"""<article class="{cls}">{rank}<div class="date">{d}</div><div><div class="type">{t}</div><a class="claim">{c}</a><div class="meta">{m}</div></div><div class="status {cl}"><span class="dot"></span>{s}</div><div class="arrow">→</div></article>"""
        )
    return "".join(out)


home = f"""<div class="shell"><section class="hero"><div><h1 class="display">La parola lascia una traccia.</h1><p class="lede">La memoria ricercabile di ciò che viene detto in pubblico: parole esatte, fonti, verifiche e cambiamenti nel tempo, senza punteggi alle persone.</p></div><aside class="searchbox"><label>Cerca nel registro</label><div class="search"><input placeholder="Dichiarazione, persona, tema o contenuto…"><button>Cerca</button></div><p class="hint">Ogni risultato mantiene il percorso verso la fonte e la storia delle revisioni.</p></aside></section><section class="section"><div class="sectionhead"><div><h2>Dichiarazioni recenti</h2><p>Un campione trasversale del registro pubblico.</p></div><a class="link">Esplora tutto →</a></div><div class="claimlist">{claim_rows()}</div></section><section class="section"><div class="sectionhead"><div><h2>Dentro una fonte</h2><p>Dal contenuto originale ai momenti pubblicati nel registro.</p></div><a class="link">Apri il contenuto →</a></div><div class="mediafeature"><div class="mediaframe"><span class="time">32:14 / 58:06</span></div><div><h3>Intervista integrale — economia, lavoro e innovazione</h3><p class="lede" style="font-size:17px">Una sola fonte, più dichiarazioni pubblicate. Ogni momento conserva la posizione originale e rimanda alla scheda completa della dichiarazione.</p><div class="moments"><div class="moment"><b>12:42</b><br>dato numerico</div><div class="moment"><b>32:14</b><br>affermazione causale</div><div class="moment"><b>48:03</b><br>confronto storico</div></div></div></div></section></div>"""
(root / "home.html").write_text(page("Home", home), encoding="utf-8")

explore = f"""<div class="shell"><header class="pagehead"><h1>Esplora il registro</h1><p class="lede">Un solo indice per dichiarazioni, persone, temi e contenuti. Parti da una parola e aggiungi filtri solo quando servono.</p></header><div class="toolbar"><div class="search"><input value="innovazione" placeholder="Cerca dichiarazioni, persone, temi, contenuti…"><button>Cerca</button></div><div class="controls"><button class="control">Tutto</button><button class="control">Dichiarazioni</button><button class="control">Persone</button><button class="control">Temi</button><button class="control">Contenuti</button><button class="control">Filtri</button><span class="count">24 risultati</span></div></div><section class="section" style="padding-top:0;border-bottom:0"><div class="claimlist">{claim_rows(True)}{claim_rows(True)}</div></section></div>"""
(root / "explore.html").write_text(page("Esplora", explore, "Esplora"), encoding="utf-8")

statement = f"""<header class="facthead"><div class="shell factgrid"><div><div class="type">Dichiarazione</div><h1 class="claimtitle">“Il nuovo sistema riduce i tempi medi di attesa di trenta giorni.”</h1><div class="factmeta"><b>Anna Serra</b><span>·</span><span>Conferenza stampa del 14 settembre 2026</span><span>·</span><span>18:42–19:21</span></div></div><aside class="factstatus"><small>In breve</small><div class="status unresolved"><span class="dot"></span>Prove insufficienti</div><p class="hint">L’esito riguarda questa dichiarazione, non la persona.</p></aside></div></header><div class="shell factbody"><article class="prose"><p class="answer">I documenti pubblicati confermano una riduzione dei tempi in due strutture, ma non consentono di sostenere che il dato valga per l’intero sistema. <span class="marker">[1]</span></p><h2>Verifica</h2><p>La dichiarazione usa un dato generale. Le evidenze disponibili descrivono campioni parziali e periodi diversi; il confronto non è sufficiente per estendere il risultato a tutto il territorio. <span class="marker">[1]</span> <span class="marker">[2]</span></p><h2>Fonti</h2><a class="sourcerow"><span class="sourceidx">[1]</span><span><b>Ministero competente</b><br><span class="meta">Rapporto trimestrale ufficiale</span></span><span class="date">15 set 2026</span><span>↗</span></a><a class="sourcerow"><span class="sourceidx">[2]</span><span><b>Ufficio statistico nazionale</b><br><span class="meta">Serie storica sui tempi di attesa</span></span><span class="date">10 set 2026</span><span>↗</span></a><h2>Contesto originale</h2><p><a class="link">Apri la conferenza stampa al minuto 18:42 ↗</a></p><h2>Traccia nel tempo</h2><p>Due dichiarazioni revisionate sullo stesso punto mostrano un successivo chiarimento. <a class="link">Apri la traccia →</a></p></article><aside class="rail"><div class="railblock"><small>Fonte originale</small><h3>Conferenza stampa</h3><p class="meta">14 settembre 2026 · video</p></div><div class="railblock"><small>Persona</small><h3>Anna Serra</h3><p class="meta">Responsabile di ente pubblico</p></div><div class="railblock"><small>Versione</small><h3>v1.2</h3><p class="meta">Aggiornata dopo l’aggiunta della fonte [2].</p></div><a class="link">Correzioni e repliche →</a></aside></div>"""
(root / "statement.html").write_text(page("Dichiarazione", statement), encoding="utf-8")

person = f"""<header class="recordhead"><div class="shell recordgrid"><div><div class="type">Persona</div><h1>Livia Ferri</h1><div class="role">Giornalista e conduttrice</div><div class="rolehistory"><span>Televisione · 2022–in corso</span><span>Podcast · 2024–in corso</span></div><p class="recordnote">Questo archivio raccoglie dichiarazioni pubbliche presenti nel registro. Non esiste un punteggio complessivo della persona.</p></div><div class="searchbox" style="border-top:0;padding-top:0"><label>Cerca nell’archivio</label><div class="search"><input placeholder="Parola o tema"><button>Cerca</button></div></div></div></header><div class="shell"><form class="filterbar"><label>Tema<select><option>Tutti</option></select></label><label>Tipo di contenuto<select><option>Tutti</option></select></label><label>Dal<input type="text" value="01/01/2026"></label><label>Al<input type="text" value="03/10/2026"></label><button class="reset">Azzera filtri</button></form><section class="section"><div class="sectionhead"><div><h2>Dichiarazioni</h2><p>In ordine cronologico, con fonte ed esito della singola scheda.</p></div></div><div class="claimlist timeline">{claim_rows()}{claim_rows()}</div></section><section class="section" style="border-bottom:0"><div class="sectionhead"><div><h2>Nel tempo</h2><p>Solo relazioni revisionate che formano una traccia utile.</p></div><a class="link">Apri una traccia →</a></div></section></div>"""
(root / "person.html").write_text(page("Archivio persona", person), encoding="utf-8")

topic = f"""<header class="recordhead"><div class="shell recordgrid"><div><div class="type">Tema</div><h1>Intelligenza artificiale</h1><p class="role">Dossier sulle dichiarazioni pubbliche riguardanti modelli, automazione, lavoro, infrastrutture e policy AI.</p><p class="recordnote">Il dossier descrive ciò che è stato dichiarato e le fonti collegate. Non classifica le persone per posizione politica o affidabilità.</p></div><div class="searchbox" style="border-top:0;padding-top:0"><label>Cerca nel tema</label><div class="search"><input placeholder="Persona, fonte o parola"><button>Cerca</button></div></div></div></header><div class="shell"><section class="section"><div class="sectionhead"><div><h2>Dichiarazioni sul tema</h2><p>Le schede pertinenti al perimetro editoriale approvato.</p></div></div><div class="claimlist">{claim_rows()}</div></section><section class="section"><div class="sectionhead"><div><h2>Tracce nel tempo</h2><p>Aggiornamenti, chiarimenti e relazioni revisionate sullo stesso punto.</p></div><a class="link">Vedi le tracce →</a></div><div class="relationnote"><b>Infrastrutture AI e consumi</b><br>Tre dichiarazioni collegate tra 2025 e 2026, con fonti primarie e aggiornamenti successivi.</div></section><section class="section" style="border-bottom:0"><div class="sectionhead"><div><h2>Contenuti e persone collegate</h2><p>Indici descrittivi per navigare il dossier, senza classifiche.</p></div></div><div class="rolehistory"><span>Interviste</span><span>Audizioni</span><span>Podcast</span><span>Documenti ufficiali</span><span>Esperti</span><span>Imprese</span></div></section></div>"""
(root / "topic.html").write_text(page("Tema", topic), encoding="utf-8")

content = f"""<header class="audithead"><div class="shell"><div class="type">Contenuto · Podcast</div><h1>Intervista integrale — economia, lavoro e innovazione</h1><div class="auditmeta"><span>Podcast pubblico</span><span>·</span><span>18 settembre 2026</span><span>·</span><span>58:06</span><span>·</span><a class="link">Fonte originale ↗</a></div></div></header><div class="shell"><div class="auditlayout"><div><div class="player"><div class="play">▶</div><div class="playercap">32:14 · momento selezionato</div></div><div class="tape"><div class="tick">00:00</div><div class="tick">12:42</div><div class="tick active">32:14</div><div class="tick">48:03</div><div class="tick">58:06</div></div><div class="momentrow"><span class="date">12:42</span><span class="q">“Nel trimestre le esportazioni sono cresciute del 6,2%.”</span><span class="status supported"><span class="dot"></span>Supportata</span></div><div class="momentrow"><span class="date">32:14</span><span class="q">“La misura ha prodotto da sola l’aumento osservato.”</span><span class="status unresolved"><span class="dot"></span>Prove insufficienti</span></div><div class="momentrow"><span class="date">48:03</span><span class="q">“Il livello attuale è il più alto degli ultimi dieci anni.”</span><span class="status imprecise"><span class="dot"></span>Imprecisa</span></div></div><aside class="auditdetail"><small>Momento selezionato · 32:14</small><h2>“La misura ha prodotto da sola l’aumento osservato.”</h2><div class="status unresolved"><span class="dot"></span>Prove insufficienti</div><p>Il contenuto originale mostra il passaggio completo; la scheda della dichiarazione contiene verifica, fonti e cronologia.</p><p style="margin-top:24px"><a class="link">Apri la dichiarazione →</a></p></aside></div></div>"""
(root / "content.html").write_text(page("Contenuto", content), encoding="utf-8")

trace = """<div class="shell"><header class="pagehead"><div class="compareintro"><div class="type">Traccia nel tempo</div><h1>Come è cambiata la previsione sulla data di avvio</h1><p class="lede">Una sequenza revisionata di dichiarazioni sullo stesso punto. La relazione descrive testi, fonti e ordine temporale; non attribuisce intenzioni.</p></div></header><section class="section" style="border-bottom:0"><div class="relationnote"><b>Relazione revisionata: aggiornamento</b><br>Gli esiti restano propri di ciascuna dichiarazione e ogni evento rimanda alla sua fonte.</div><div class="comparetimeline"><article class="event"><div class="eventdate">12 feb<br>2025</div><blockquote>“Il progetto entrerà in funzione entro la fine dell’anno.”</blockquote><div class="eventmeta">Davide Conti · Intervista televisiva · fonte originale disponibile</div><div class="eventstatus status supported"><span class="dot"></span>Supportata nel contesto disponibile</div></article><article class="event"><div class="eventdate">18 set<br>2026</div><blockquote>“La fase operativa partirà nel primo trimestre del prossimo anno.”</blockquote><div class="eventmeta">Davide Conti · Conferenza pubblica · fonte originale disponibile</div><div class="eventstatus status imprecise"><span class="dot"></span>Aggiornamento successivo</div></article><article class="event"><div class="eventdate">02 ott<br>2026</div><blockquote>Correzione pubblicata: la nuova data sostituisce la previsione precedente nel record, che resta consultabile.</blockquote><div class="eventmeta">Nota di aggiornamento · cronologia versionata</div></article></div></section></div>"""
(root / "trace.html").write_text(page("Traccia nel tempo", trace), encoding="utf-8")

method = """<div class="shell method"><article><h1>Una verifica deve poter essere ripercorsa.</h1><p class="methodintro">Dichiarazioni Pubbliche separa acquisizione, evidenza, verifica, revisione e pubblicazione. Una fase completata non autorizza automaticamente la successiva.</p><div class="step"><div class="stepnum">01</div><div><h2>Partire dalle parole esatte</h2><p>Conserviamo formulazione originale, fonte, data e posizione nel contenuto. La normalizzazione aiuta a confrontare i record, ma non sostituisce ciò che è stato detto.</p></div></div><div class="step"><div class="stepnum">02</div><div><h2>Usare fonti adatte alla domanda</h2><p>Preferiamo fonti primarie o ufficiali quando sono autorevoli per la domanda specifica. Ogni evidenza pubblicata mantiene un percorso verificabile verso l’origine.</p></div></div><div class="step"><div class="stepnum">03</div><div><h2>Separare evidenza e valutazione</h2><p>Le prove vengono raccolte e approvate prima della conclusione. Se non bastano, lo stato resta irrisolto o non viene pubblicato.</p></div></div><div class="step"><div class="stepnum">04</div><div><h2>Conservare tempo, correzioni e repliche</h2><p>Una correzione non cancella silenziosamente ciò che c’era prima. Le versioni restano tracciate, con data e motivazione dell’aggiornamento.</p></div></div></article><aside class="principles"><h3>Principi del record</h3><div><b>Nessun punteggio alle persone</b><span>La valutazione appartiene alla singola dichiarazione.</span></div><div><b>Incertezza esplicita</b><span>“Non risolta” e “prove insufficienti” sono risultati legittimi.</span></div><div><b>Fonte a un passo</b><span>Ogni esito pubblico deve poter essere ricondotto alle evidenze approvate.</span></div><div><b>Correzioni versionate</b><span>Gli aggiornamenti aggiungono storia al record, non la cancellano.</span></div></aside></div>"""
(root / "method.html").write_text(page("Metodo", method, "Metodo"), encoding="utf-8")

utility = """<div class="shell method"><article><div class="type">Pagina di fiducia · template condiviso</div><h1>Correzioni, dati e progetto senza creare un altro prodotto.</h1><p class="methodintro">Le pagine di fiducia usano una grammatica documentale comune. Cambiano contenuto e call to action, non il modello di interazione.</p><div class="step"><div class="stepnum">A</div><div><h2>Correzioni</h2><p>Registro cronologico delle modifiche materiali, delle rianalisi e delle repliche pubbliche, con link alla versione interessata.</p></div></div><div class="step"><div class="stepnum">B</div><div><h2>Dati & API</h2><p>Punto di accesso umano a JSON, JSON-LD, OpenAPI, feed, licenze e versioni del contratto pubblico.</p></div></div><div class="step"><div class="stepnum">C</div><div><h2>Progetto</h2><p>Missione, governance, repository open source, indipendenza, responsabilità editoriale e contatti.</p></div></div></article><aside class="principles"><h3>Regola</h3><div><b>Un solo template</b><span>Queste route non giustificano tre nuovi sistemi di pagina.</span></div><div><b>Contribuisci è differito</b><span>La route nasce solo quando i gate anti-abuso e legali sono pronti.</span></div></aside></div>"""
(root / "utility.html").write_text(page("Pagine di fiducia", utility), encoding="utf-8")

canonical = {"home.html", "explore.html", "statement.html", "person.html", "topic.html", "content.html", "trace.html", "method.html", "utility.html"}
for old in root.glob("*.html"):
    if old.name not in canonical:
        old.unlink()

print("built", len(canonical), "canonical mockups")
