window.DICHIARAZIONI_PUBBLICHE_DEMO = {
  audit: {
    id: "raffagiulians-bollo-2026",
    creator: "Raffaele Giuliani",
    handle: "@raffagiulians",
    title: "Gioggia ha “abolito” (sospeso) il bollo. Cosa cambia? Nulla.",
    auditedAt: "21 settembre 2026",
    duration: "7:24",
    claimCount: 36,
    evidenceCount: 23,
    segmentCount: 84,
    transcriptModel: "Groq Whisper Large v3 Turbo",
    aggregateScore: false,
  },
  claims: [
    { id: "C01", time: "0:00", type: "Historical attribution", assessment: "MISSING_CONTEXT", evidence: 2 },
    { id: "C02", time: "0:07", type: "Current policy", assessment: "SUPPORTED", evidence: 1 },
    { id: "C03", time: "0:28", type: "Motive attribution", assessment: "UNSUBSTANTIATED", evidence: 0 },
    { id: "C04", time: "0:34", type: "Legal policy status", assessment: "SUPPORTED_WITH_CONTEXT", evidence: 2 },
    { id: "C05", time: "0:53", type: "Motive attribution", assessment: "UNSUBSTANTIATED", evidence: 1 },
    { id: "C06", time: "1:04", type: "Election prediction", assessment: "PREDICTION_PENDING", evidence: 0 },
    { id: "C07", time: "1:44", type: "Numeric statistic", assessment: "SUPPORTED", evidence: 1, sensitive: true },
    { id: "C08", time: "1:44", type: "Numeric statistic", assessment: "SUPPORTED", evidence: 2, sensitive: true },
  ],
  assessmentCounts: [
    ["SUPPORTED", 13],
    ["SUPPORTED_WITH_CONTEXT", 4],
    ["UNVERIFIABLE_AS_STATED", 4],
    ["UNSUBSTANTIATED", 3],
    ["MISSING_CONTEXT", 2],
    ["CONTRADICTED", 2],
    ["UNSUPPORTED_INFERENCE", 2],
    ["PARTIALLY_SUPPORTED", 2],
    ["NOT_FACT_CHECKABLE", 2],
    ["PREDICTION_PENDING", 1],
    ["MISATTRIBUTED", 1],
  ],
  pulp: {
    title: "Beppe Grillo a Pulp Podcast. | Pulp Podcast #64",
    date: "21 settembre 2026",
    duration: "78 min",
    segments: 1981,
    characters: 67821,
    sensitivePrefilter: 365,
    transcript: "caption italiana automatica originale",
    state: "TRANSCRIPT_READY · CLAIM_EXTRACTION_BLOCKED",
  },
};
